title: Songhee Kim, Ph.D.
url: "https://songhee-kim.github.io"
#baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: index
   #link: "/researcher/"
 - name: "Projects"
   link: "projects"
 - name: "CV"
   link: "CV_SongheeKim.pdf"
 - name: "Contact"
   link: "contact"
